# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: Build bridgelink

on:
  push:
    branches:
      - bridgelink_development
  pull_request:
    branches:
      - bridgelink_development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          java-package: 'jdk+fx'
          distribution: 'zulu'

      - name: Build Bridgelink - signed
        if: github.ref == 'refs/heads/bridgelink_development'
        working-directory: server
        run: ant -f mirth-build.xml

      - name: Build Bridgelink - unsigned
        if: github.ref != 'refs/heads/bridgelink_development'
        working-directory: server
        run: ant -f mirth-build.xml -DdisableSigning=true

      - name: Package distribution
        run: tar czf bridgelink.tar.gz -C server/ setup --transform 's|^setup|bridgelink/|'

      - name: Create artifact
        uses: actions/upload-artifact@v4
        with:
          name: bridgelink-build
          path: bridgelink.tar.gz
